---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# VicmapR

<!-- badges: start -->
<!-- badges: end -->

The goal of VicmapR is to provide functions to easily access Victorin Government spatial data through their WFS (Web Feature Service).

## Installation

You can install the the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("JustinCally/VicmapR")
```
## Example

### Searching for data

```{r example}
library(VicmapR)
## basic example code

# Create new client
VicmapClient <- newClient()

listLayers(VicmapClient, pattern = stringr::regex("trees", ignore_case = T))
```

### Reading in data

```{r}
data <- read_layer_sf(layer_name = "datavic:VMHYDRO_WATERCOURSE_DRAIN",
                      boundbox = boundbox(xmin = 144.25, 
                                          ymin = -38.44, 
                                          xmax = 144.50,  
                                          ymax = -38.25),  
                      filter = "HIERARCHY = 'L'")

str(data)
```

