---
title: "How to Query Vicmap Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to Query Vicmap Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dplyr)
library(VicmapR)
library(sf)
```

# How to Query Data

```{r query, eval = FALSE}
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN")
```

```{r query_collect, eval = FALSE}
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", wfs_version = "1.0.0") %>%
  head(50) %>%
  collect()
```

```{r show_query, eval = FALSE}
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", wfs_version = "1.0.0") %>%
  head(50) %>%
  show_query()
```

```{r filter, eval = FALSE}
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", wfs_version = "1.0.0") %>%
 filter(HIERARCHY == "L", PFI == 8553127) %>%
  collect()
```

```{r paginate, eval = FALSE}
data <- vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", wfs_version = "1.0.0") %>%
  collect()
```


```{r filter_spatial, eval = FALSE}
melbourne <- st_read(system.file("shapes/melbourne.geojson", package="VicmapR"))

vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326) %>%
#  filter(HIERARCHY == "L") %>%
  filter(BBOX(sf::st_bbox(melbourne))) %>%
  collect() %>%
  plot(max.plot = 2, lwd = 10, cex = 10)
```

```{r filter_spatial_2,eval=FALSE}
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326, wfs_version = "1.0.0") %>%
  filter(VicmapR::DWITHIN(melbourne %>% sf::st_centroid(), distance = 1000, units = "meters")) %>%
  show_query()
  
  library(lineprof)

prof <- lineprof({vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326, wfs_version = "1.0.0") %>%
  filter(VicmapR::DWITHIN(melbourne %>% sf::st_centroid(), distance = 1000, units = "meters")) %>%
  collect()})

shine(prof)
#  filter(HIERARCHY == "L") %>%
data <- vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326, wfs_version = "1.0.0") %>%
  filter(CROSSES(melbourne %>% polygonFormat())) %>%
  collect() 


# points <- list(melbz = c(144.9436,-37.81073))
# 
# closest_feature <- lapply(points, function(y) {
#   
# n_hits <- 0    
# i <- 0
# 
# while(n_hits < 1) { 
#   i <- i + 1
#   x <- 100*i
# data <- paste0("http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wfs?service=wfs&version=1.0.0&request=GetFeature&typeNames=datavic%3AVMHYDRO_WATERCOURSE_DRAIN&outputFormat=application%2Fjson&count=70000&srsName=EPSG%3A4326&CQL_FILTER=%28DWITHIN%28SHAPE%2C%20POINT%20%28",y[1],"%20", y[2],"%29%2C%20", x,"%2C%20meters%29%29") %>% sf::read_sf()
# n_hits <- nrow(data)
# 
# }
# point_poly <- sf::st_as_sf(x = data.frame(long = y[1], lat = y[2]),
#                            coords = c("long", "lat")) %>% sf::`st_crs<-`(4326)
# 
# data$distance_from_point <- sf::st_distance(point_poly, 
#                                             data, by_element = TRUE) 
# 
# data <- data %>%
#   dplyr::arrange(distance_from_point) %>%
#   dplyr::slice(1)
# 
# # nearest_points <- sf::st_nearest_points(point_poly, 
# #                                         data) %>% sf::st_cast("MULTIPOINT") %>%
# #   as.data.frame()
# 
# return(data)
# })

```


```{r loop_dwithin, eval=FALSE}
melbourne <- st_read(system.file("shapes/melbourne.geojson", package="VicmapR"))

some_point <- melbourne %>% sf::st_centroid()

# How many hits 
vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326, wfs_version = "1.0.0") %>%
  filter(VicmapR::DWITHIN(some_point, distance = 2000, units = "meters")) %>%
  feature_hits()

vicmap_query(layer = "datavic:VMHYDRO_WATERCOURSE_DRAIN", CRS = 4326, wfs_version = "1.0.0") %>%
  filter(VicmapR::DWITHIN(some_point, distance = 1000, units = "meters")) %>%
  collect()
```

