library(httr)
library(ows4R)
library(sf)
library(dplyr)
library(stringr)
library(purrr)
#### Setup WFSClient Base URL ####
wfs_url <- "http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wms"

#' New WFSClient
#' 
#' @description Establishes a new WFSClient for Victoria's spatial data using \link{ows4R}[WFSClient]
#'
#' @param version Version of WFS to use
#' @param ... Additional arguments passed to \link{ows4R}[WFSClient]$new
#'
#' @return Object of \link{R6}[R6Class] with methods for interfacing an OGC Web Feature Service.
#' @export
#'
#' @examples
#' VicmapClient <- newClient()

newClient <- function(version = "1.1.1", ...) {

ows4R::WFSClient$new(wfs_url, 
                     serviceVersion = version, 
                     ...)
}

#' List available WFS layers
#' @description Wraps `getFeatureTypes` from \link{ows4r}[WFSClient] and allows for string searching of layers
#'
#' @param Client WFSClient generated by \link{VicmapR}[newClient]
#' @param ... Additional arguments passed to \link{stringr}[str_detect]. The `pattern` argument can be used to search for specific layers with matching names or titles. 
#'
#' @return data.frame
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listLayers(VicmapClient, pattern = stringr::regex("flood height contour", ignore_case = TRUE))

listLayers <- function(Client, ...) {
df <- Client$getFeatureTypes(pretty = TRUE) 

if(hasArg('pattern')){
df <- dplyr::filter_all(df, dplyr::any_vars(stringr::str_detect(string = ., ...)))
  }
return(df)
}  



#' list data fields for WFS layer
#'
#' @param layer_name character; name of the WFS layer
#' @rdname listLayers
#'
#' @return character; fields/columns of data
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listFields(VicmapClient, "datavic:VMLITE_TR_AIRPORT")
listFields <- function(Client, layer_name) {
  Client$
    getCapabilities()$
    findFeatureTypeByName(layer_name)$
    getDescription() %>%
    purrr::map_chr(function(x){x$getName()})
}

boundbox <- function(xmin, ymin, xmax, ymax) {
  paste(c(xmin, ymin, xmax, ymax), collapse = ",")
}


read_layer_sf <- function(layer_name, filter = NULL, CRS = 4283, boundbox = NULL, ...) {
  url <- httr::parse_url(wfs_url)
  url$query <- list(service = "wfs",
                    version = "2.0.0",
                    request = "GetFeature",
                    typename = layer_name,
                    CQL_FILTER = filter,
                    BBOX = boundbox,
                    srsName = paste0("EPSG:", CRS)) %>% purrr::discard(is.null)
  
  request <- httr::build_url(url)
  
  print(request)
  
  return(sf::read_sf(request, ...))
  
}


data <- read_layer_sf("datavic:VMLITE_TR_AIRPORT", boundbox = boundbox(xmin = 144.05, ymin = -38.44, xmax = 145.59, ymax = -37.19))
