library(httr)
library(ows4R)
library(sf)
library(dplyr)
library(stringr)
library(purrr)
#### Setup WFSClient Base URL ####
wfs_url <- "http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wms"

#' New WFSClient
#' 
#' @description Establishes a new WFSClient for Victoria's spatial data using \link{ows4R}[WFSClient]
#'
#' @param version Version of WFS to use
#' @param ... Additional arguments passed to \link{ows4R}[WFSClient]$new
#'
#' @return Object of \link{R6}[R6Class] with methods for interfacing an OGC Web Feature Service.
#' @export
#'
#' @examples
#' VicmapClient <- newClient()

newClient <- function(version = "1.1.1", ...) {

ows4R::WFSClient$new(wfs_url, 
                     serviceVersion = version, 
                     ...)
}

#' List available WFS layers
#' @description Wraps `getFeatureTypes` from \link{ows4r}[WFSClient] and allows for string searching of layers
#'
#' @param Client WFSClient generated by \link{VicmapR}[newClient]
#' @param ... Additional arguments passed to \link{stringr}[str_detect]. The `pattern` argument can be used to search for specific layers with matching names or titles. 
#'
#' @return data.frame
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listLayers(VicmapClient, pattern = stringr::regex("flood height contour", ignore_case = TRUE))

listLayers <- function(Client, ...) {
df <- Client$getFeatureTypes(pretty = TRUE) 

if(hasArg('pattern')){
df <- dplyr::filter_all(df, dplyr::any_vars(stringr::str_detect(string = ., ...)))
  }
return(df)
}  



#' list data fields for WFS layer
#'
#' @param layer_name character; name of the WFS layer
#' @rdname listLayers
#'
#' @return character; fields/columns of data
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listFields(VicmapClient, "datavic:VMLITE_TR_AIRPORT")
listFields <- function(Client, layer_name) {
  Client$
    getCapabilities()$
    findFeatureTypeByName(layer_name)$
    getDescription() %>%
    purrr::map_chr(function(x){x$getName()})
}


#' Formats boundbox for WFS query
#' @description Convenience function that formats a spatial bounding box into a character string that can be passed to the WFS query. 
#' The function accepts either a `bbox` from \link{sf}[st_bbox] or the coordinates for the box edges (`xmin`, `ymin`, `xmax`, `ymax`).
#'
#' @param xmin numeric; minimum x coordinate (longitude)
#' @param ymin numeric; minimum y coordinate (latitude)
#' @param xmax numeric; maximum x coordinate (longitude)
#' @param ymax numeric; maximum y coordinate (latitude)
#' @param st_bbox bbox; object generated using \link{sf}[st_bbox]
#'
#' @return character string formatted for WFS query and use in \link{VicmapR}[read_layer_sf]
#' @export
#'
#' @examples
#' #### Using an sf object ####
#' sf_data <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
#' boundbox(st_bbox = sf::st_bbox(sf_data))
#' 
#' #### Using coordinates ####
#' boundbox(xmin = 144.05, ymin = -38.44, xmax = 144.50, ymax = -38.10)
boundbox <- function(xmin, ymin, xmax, ymax, st_bbox = NULL) {
  
  if(!is.null(st_bbox)) {
    if(class(st_bbox) != "bbox") {
      stop("st_bbox is not of class 'bbox'. Use sf::st_bbox to generate a valid bbox")
    }
    box <- paste(st_bbox, collapse = ",")
  } else {
  box <- paste(c(xmin, ymin, xmax, ymax), collapse = ",")
  }
  return(box)
}


read_layer_sf <- function(layer_name, filter = NULL, CRS = 4283, boundbox = NULL, ...) {
  
  # Set up URL query and request
  url <- httr::parse_url(wfs_url)
  url$query <- list(service = "wfs",
                    version = "1.0.0",
                    request = "GetFeature",
                    typename = layer_name,
                    srsName = paste0("EPSG:", CRS),
                    BBOX = boundbox, 
                    CQL_FILTER = filter) %>% purrr::discard(is.null)
  
  request <- httr::build_url(url)
  
  # Return an sf object
  return(sf::read_sf(request, ...))
  
}

# CQL filter and bbox are mutually exclusive. Need to get the bbox in cql format (therefore need to find the )

data <- read_layer_sf("datavic:VMHYDRO_WATERCOURSE_DRAIN", 
                      boundbox = boundbox(xmin = 144.05, ymin = -38.44, xmax = 144.50, ymax = -38.10), 
                      filter = "UFI = 2915212")

