
#' List available WFS layers
#' @description Wraps `getFeatureTypes` from \link[ows4R]{WFSClient} and allows for string searching of layers
#'
#' @param Client WFSClient generated by \link[VicmapR]{newClient}
#' @param ... Additional arguments passed to \link[stringr]{str_detect}. The `pattern` argument can be used to search for specific layers with matching names or titles. 
#'
#' @return data.frame
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listLayers(VicmapClient, pattern = stringr::regex("flood height contour", ignore_case = TRUE))

listLayers <- function(Client, ...) {
  df <- Client$getFeatureTypes(pretty = TRUE) 
  
  if(methods::hasArg('pattern')){
    df <- dplyr::filter_all(df, dplyr::any_vars(stringr::str_detect(string = ., ...)))
  }
  return(df)
}  



#' list data fields for WFS layer
#'
#' @param layer_name character; name of the WFS layer
#' @rdname listLayers
#'
#' @return character; fields/columns of data
#' @export
#'
#' @examples
#' VicmapClient <- newClient()
#' listFields(VicmapClient, "datavic:VMLITE_TR_AIRPORT")
listFields <- function(Client, layer_name) {
  Client$
    getCapabilities()$
    findFeatureTypeByName(layer_name)$
    getDescription(pretty = T) %>%
    .$name
}

